name: 'Lint and Fix Code'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint and Fix Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 autopep8

    - name: Run Linter (Check for issues)
      run: |
        flake8 . || echo "Linting completed with warnings"

    - name: Auto-fix Python issues with autopep8
      run: |
        autopep8 --in-place --recursive .
        echo "Auto-fixed Python files"

    - name: Commit and push changes if needed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "chore: apply autopep8 auto-fixes" || echo "No changes to commit"
        git push || echo "No changes to push"

  lint_js:
    name: Lint and Fix JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install ESLint
      run: |
        npm install eslint --global
        npm install eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise --global

    - name: Run Linter (Check for issues)
      run: |
        find ./server/database -name "*.js" -exec eslint {} + || echo "Linting completed with warnings"

    - name: Auto-fix JavaScript issues with ESLint
      run: |
        find ./server/database -name "*.js" -exec eslint --fix {} +
        echo "Auto-fixed JS files"

    - name: Commit and push changes if needed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "chore: apply ESLint auto-fixes" || echo "No changes to commit"
        git push || echo "No changes to push"
